### ISSUE TITLE
Native Arsenal is broken

### ISSUE THREAD

**Issue by thunderah** [7th-ranger-group/7r-liberation-chernarus#2]
no outfit can be used on the arsenal, on close it removes all clothes and gear leaving a stripped unit

**Comment by xSayZ** [comment]
It's because the Native Arsenal doesn't have those items to the "item whitelist".

**Comment by sigfriedseldeslachts** [comment]
I would need classnames of everything that is allowed. Takes a long time, if anyone is wanting to send those we can add them.
